# simple Dockerfile with set defined Timezone in container

FROM python:3.11.0-alpine3.15
ENV TZ="Asia/Yekaterinburg"
RUN apt-get update && apt-get upgrade && apt-get install tzdata -y && cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata
